name: In Situ Vis

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-insituvis
  cancel-in-progress: true

jobs:
  ascent:
    name: Ascent
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    env:
      CXX: g++
      CC: gcc
      CMAKE_PREFIX_PATH: /ascent/install/lib/cmake/
    container:
      image: alpinedav/ascent:0.8.0
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: |
        . /ascent_docker_setup_env.sh
        cmake -S . -B build   \
            -DNyx_HYRDO=ON \
            -DUSE_ASCENT_INSITU=TRUE \
            -DNyx_HEATCOOL=ON 
        cmake --build build --parallel 2
    - name: Build
      run: |
        . /ascent_docker_setup_env.sh
        cmake --build build -j 2
    - name: Test
      run: |
        cp Nyx/Lya/inputs .
        cp Nyx/Lya/ascent_actions.yaml .
        mpiexec -n 2 ./nyx inputs
    - uses: actions/upload-artifact@v2
      with:
        name: ascent-test-artifacts
        path: |
          *.png
        if-no-files-found: error
